"""Tests for the sleep FIT parser.

Verifies that ingest_sleep against an Instinct 3-shaped sleep file produces a
sleep_sessions row with correct timestamps + duration, sleep_stages rows
with correctly-labeled stages from the SleepLevel enum
(0=unmeasurable, 1=awake, 2=light, 3=deep, 4=rem), and a non-NULL
sleep_score (best-candidate from sleep_assessment.f3).

The fixture is SYNTHETIC — generated by tests/fixtures/build_fit_fixtures.py,
not pulled off a watch. Its message/field *structure* mirrors the real thing
and is what these tests pin down; its *values* are invented. Never treat it
as ground truth when reverse-engineering field semantics (see PARSER_NOTES.md).
"""

from __future__ import annotations

import json
from pathlib import Path

from garmin_dump.db.connection import Database
from garmin_dump.db.repo import (
    DeviceUpsert,
    SyncKey,
    mark_sync_verified,
    upsert_device,
    upsert_sync_pending,
)
from garmin_dump.ingest.fit_reader import bucket_file
from garmin_dump.ingest.sleep import ingest_sleep

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"
SLEEP_FIXTURE = FIXTURES / "sleep_F5I94001.fit"
VALID_STAGES = {"unmeasurable", "awake", "light", "deep", "rem"}


def _seed(db: Database) -> tuple[int, int]:
    """Insert one device + one verified sync_log row, return (device_id, sync_id)."""
    device_id = upsert_device(
        db.conn,
        DeviceUpsert(
            serial="3509067685",
            unit_id="test_unit",
            part_number=None,
            model="Instinct 3",
            software_version="521",
        ),
    )
    sync_id = upsert_sync_pending(
        db.conn,
        SyncKey(
            device_id=device_id,
            remote_parent="Sleep",
            filename="sleep_F5I94001.fit",
            size_bytes=SLEEP_FIXTURE.stat().st_size,
        ),
        category="sleep",
    )
    mark_sync_verified(
        db.conn,
        sync_id,
        sha256="0" * 64,
        local_path=str(SLEEP_FIXTURE),
    )
    return device_id, sync_id


def test_ingest_sleep_writes_session_row(tmp_path: Path) -> None:
    db_path = tmp_path / "test.db"
    with Database(db_path) as db:
        device_id, sync_id = _seed(db)
        buckets = bucket_file(SLEEP_FIXTURE)
        sleep_id = ingest_sleep(
            db.conn, sync_id=sync_id, device_id=device_id, buckets=buckets
        )
        assert sleep_id is not None and sleep_id > 0

        row = db.conn.execute(
            "SELECT * FROM sleep_sessions WHERE sleep_id = ?", (sleep_id,)
        ).fetchone()
        assert row is not None
        assert row["start_utc"]
        assert row["end_utc"]
        assert row["start_utc"] <= row["end_utc"]
        # Duration should be plausible: a 12-stage sleep file spans at most a
        # few hours, but our fixture is short (small file). Just assert it's
        # a positive integer or None.
        if row["duration_s"] is not None:
            assert row["duration_s"] >= 0


def test_ingest_sleep_writes_stage_rows(tmp_path: Path) -> None:
    db_path = tmp_path / "test.db"
    with Database(db_path) as db:
        device_id, sync_id = _seed(db)
        buckets = bucket_file(SLEEP_FIXTURE)
        sleep_id = ingest_sleep(
            db.conn, sync_id=sync_id, device_id=device_id, buckets=buckets
        )
        assert sleep_id is not None

        stages = db.conn.execute(
            """
            SELECT start_utc, end_utc, stage
            FROM sleep_stages WHERE sleep_id = ?
            ORDER BY start_utc
            """,
            (sleep_id,),
        ).fetchall()
        # Fixture file has 12 sleep_level messages.
        assert len(stages) == 12
        # Every label must be in the documented enum.
        for s in stages:
            assert s["stage"] in VALID_STAGES, f"unexpected stage label {s['stage']!r}"
            assert s["start_utc"] <= s["end_utc"]
        # Stages must be time-ordered (the SQL ORDER BY guarantees it; this
        # double-checks no two rows share the same start time except trivially).
        for i in range(1, len(stages)):
            assert stages[i]["start_utc"] >= stages[i - 1]["start_utc"]


def test_ingest_sleep_records_sleep_score_and_raw_json(tmp_path: Path) -> None:
    db_path = tmp_path / "test.db"
    with Database(db_path) as db:
        device_id, sync_id = _seed(db)
        buckets = bucket_file(SLEEP_FIXTURE)
        sleep_id = ingest_sleep(
            db.conn, sync_id=sync_id, device_id=device_id, buckets=buckets
        )
        row = db.conn.execute(
            "SELECT sleep_score, raw_json FROM sleep_sessions WHERE sleep_id = ?",
            (sleep_id,),
        ).fetchone()
        # Sleep score may be None if the fixture's f3 happened to be out of
        # range (we documented this risk in the plan), but if present it must
        # be a percentile.
        if row["sleep_score"] is not None:
            assert 0 <= int(row["sleep_score"]) <= 100
        # raw_json must contain the three keys we promised.
        payload = json.loads(row["raw_json"])
        assert "sleep_assessment" in payload
        assert "sleep_data_info" in payload
        assert "restless_moments" in payload


def test_ingest_sleep_is_idempotent(tmp_path: Path) -> None:
    """Running ingest twice for the same file should not duplicate rows."""
    db_path = tmp_path / "test.db"
    with Database(db_path) as db:
        device_id, sync_id = _seed(db)
        buckets = bucket_file(SLEEP_FIXTURE)
        first_id = ingest_sleep(
            db.conn, sync_id=sync_id, device_id=device_id, buckets=buckets
        )
        second_id = ingest_sleep(
            db.conn, sync_id=sync_id, device_id=device_id, buckets=buckets
        )
        assert first_id == second_id

        n_sessions = db.conn.execute(
            "SELECT COUNT(*) FROM sleep_sessions"
        ).fetchone()[0]
        assert n_sessions == 1

        n_stages = db.conn.execute(
            "SELECT COUNT(*) FROM sleep_stages WHERE sleep_id = ?", (first_id,)
        ).fetchone()[0]
        assert n_stages == 12  # not 24 — the parser purges before re-insert
